/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-07-25 19:55:45 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:5432/stakes-debug -t events -t logs -t tapes -s public
 *
 */


export namespace eventsFields {
    export type event_id = number | null;
    export type production_no = string | null;
    export type phase = string | null;
    export type venue = string | null;
    export type event_date = string | null;
    export type image_filename = string | null;
    export type logged_by = string | null;
    export type sport = string | null;
    export type originator = string | null;
    export type title = string | null;
    export type created_date = string | null;
    export type name = string | null;
    export type event_notes = string | null;
    export type modified_date = string | null;

}

export interface events {
    event_id: eventsFields.event_id;
    production_no: eventsFields.production_no;
    phase: eventsFields.phase;
    venue: eventsFields.venue;
    event_date: eventsFields.event_date;
    image_filename: eventsFields.image_filename;
    logged_by: eventsFields.logged_by;
    sport: eventsFields.sport;
    originator: eventsFields.originator;
    title: eventsFields.title;
    created_date: eventsFields.created_date;
    name: eventsFields.name;
    event_notes: eventsFields.event_notes;
    modified_date: eventsFields.modified_date;

}

export namespace logsFields {
    export type event_id = number | null;
    export type log_id = string | null;
    export type timecode = string | null;
    export type description = string | null;
    export type tape_no = string | null;

}

export interface logs {
    event_id: logsFields.event_id;
    log_id: logsFields.log_id;
    timecode: logsFields.timecode;
    description: logsFields.description;
    tape_no: logsFields.tape_no;

}

export namespace tapesFields {
    export type barcode = string | null;
    export type production_no = string | null;
    export type tape_no = string | null;
    export type status = string | null;
    export type format = string | null;
    export type tv_standard = string | null;
    export type a1 = string | null;
    export type a2 = string | null;
    export type a3 = string | null;
    export type a4 = string | null;
    export type record_date = string | null;
    export type notes = string | null;
    export type in_tx = string | null;
    export type in_vtlib = string | null;
    export type sub_title = string | null;
    export type title = string | null;
    export type itsproduction_no = string | null;
    export type created_date = string | null;
    export type modified_date = string | null;

}

export interface tapes {
    barcode: tapesFields.barcode;
    production_no: tapesFields.production_no;
    tape_no: tapesFields.tape_no;
    status: tapesFields.status;
    format: tapesFields.format;
    tv_standard: tapesFields.tv_standard;
    a1: tapesFields.a1;
    a2: tapesFields.a2;
    a3: tapesFields.a3;
    a4: tapesFields.a4;
    record_date: tapesFields.record_date;
    notes: tapesFields.notes;
    in_tx: tapesFields.in_tx;
    in_vtlib: tapesFields.in_vtlib;
    sub_title: tapesFields.sub_title;
    title: tapesFields.title;
    itsproduction_no: tapesFields.itsproduction_no;
    created_date: tapesFields.created_date;
    modified_date: tapesFields.modified_date;

}
